#!/bin/sh

usage() {
  name="${0##*/}"
  echo "Provide the credentials to Canvas."
  echo "By default, $name syncs to your default download location."

  echo "Usage:"
  echo "  $name -v -k [API_KEY] SYNC_DIR"
  exit 1
}

DEBUG() {
  if [ "$debug" = true ]; then
    echo "$@"
  fi
}

###############################################################################

for arg in "$@"; do
  shift
  case "$arg" in
    '--help')     set -- "$@" '-h'   ;;
    '--debug')    set -- "$@" '-d'   ;;
    '--clobber')  set -- "$@" '-c'   ;;
    '--key')      set -- "$@" '-k'   ;;
    *)            set -- "$@" "$arg" ;;
  esac
done

key=
clobber=false
debug=false
while getopts "hdck:u:p:" o; do
  case "$o" in
    d) debug=true ;;
    c) clobber=true ;;
    k) key="$OPTARG";;
    h | *) usage;;
  esac
done
shift $((OPTIND-1))

if [ -z "$key" ]; then
  echo "Please provide Canvas API key."
  exit 1
fi

download_dir="${XDG_DOWNLOAD_DIR:-$HOME/Downloads}"
if [ -n "$1" ]; then
  download_dir="$1"
fi
mkdir -p "$download_dir"
cd "$download_dir" || exit 1

###############################################################################

CANVAS_DOMAIN="https://canvas.nus.edu.sg"
AUTH_API="/api/v1/users/self"
COURSES_API="/api/v1/courses"
FOLDERS_API="/api/v1/folders"

###############################################################################

_curl() {
  curl -s \
    -H "Authorization: Bearer $key" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" \
    "$@"
}

_wget() {
  if [ "$clobber" = true ]; then
    wget -q --show-progress "$@"
  else
    wget -q -nc --show-progress "$@"
  fi
}

authenticate() {
  printf "Verifying Canvas API key... "
  data=$(_curl "$CANVAS_DOMAIN$AUTH_API")
  if [ "$(echo "$data" | jq -r 'has("errors")')" = true ]; then
    printf "\nAuthentication failed. ";
    echo "$data" | jq -r '.errors[0].message'
    exit 1;
  fi
  echo "Success!"
}

sync_canvas_files() {
  printf "Syncing Canvas files...\n"

  _curl "$CANVAS_DOMAIN$COURSES_API" |\
    jq -r '.[] | select(.course_code != null) | .name, .id, .course_code' |\
  while read -r course_name; do
    echo "$course_name"
    read -r course_id
    read -r course_code
    course_code="${course_code%%/*}"
    mkdir -p "$course_code"

    _curl "$CANVAS_DOMAIN$COURSES_API/$course_id/files" |\
      jq -r 'arrays | .[] | select(.locked == false) | .url, .folder_id, .display_name' |\
    while read -r url; do
      read -r folder_id
      read -r file_name

      folder_name="$(eval echo '$'__yans_folder_"$folder_id")"
      if [ -z "$folder_name" ]; then
        folder_name="$(_curl "$CANVAS_DOMAIN$FOLDERS_API/$folder_id" | jq -r '.full_name')"
        folder_name="${folder_name#course files/}"
        eval "__yans_folder_$folder_id='$folder_name'"
      fi

      mkdir -p "$course_code/$folder_name"
      _wget -O "$course_code/$folder_name/$file_name" "$url"
    done
  done
}

main() {
  authenticate && sync_canvas_files
}

main
